INSERT into DiasClase VALUES('Yoga','7');
INSERT into DiasClase VALUES('Yoga','4');
INSERT into DiasClase VALUES('Yoga','3');
INSERT into DiasClase VALUES('Yoga','5');
INSERT into DiasClase VALUES('Yoga','2');
INSERT into DiasClase VALUES('Yoga','6');
INSERT into DiasClase VALUES('Yoga','1');
INSERT into DiasClase VALUES('Danza Árabe','1');
INSERT into DiasClase VALUES('Danza Árabe','7');
INSERT into DiasClase VALUES('Boxeo','7');
INSERT into DiasClase VALUES('Boxeo','4');
INSERT into DiasClase VALUES('Twerk','1');
INSERT into DiasClase VALUES('Twerk','6');
INSERT into DiasClase VALUES('Twerk','3');
INSERT into DiasClase VALUES('Twerk','5');
INSERT into DiasClase VALUES('Twerk','2');
INSERT into DiasClase VALUES('Zumba','2');
INSERT into DiasClase VALUES('Zumba','7');
INSERT into DiasClase VALUES('Zumba','4');
INSERT into DiasClase VALUES('Zumba','3');
INSERT into DiasClase VALUES('Zumba','5');
INSERT into DiasClase VALUES('Zumba','1');
